
export const alphabetical = [
  { label: "Select letters", value: "" },
  { label: "A", value: "a" },
  { label: "B", value: "b" },
  { label: "C", value: "c" },
  { label: "D", value: "d" },
  { label: "E", value: "e" },
  { label: "F", value: "f" },
  { label: "G", value: "g" },
  { label: "H", value: "h" },
  { label: "I", value: "i" },
  { label: "J", value: "j" },
  { label: "K", value: "k" },
  { label: "L", value: "l" },
  { label: "M", value: "m" },
  { label: "N", value: "n" },
  { label: "O", value: "o" },
  { label: "P", value: "p" },
  { label: "Q", value: "q" },
  { label: "R", value: "r" },
  { label: "S", value: "s" },
  { label: "T", value: "t" },
  { label: "U", value: "u" },
  { label: "V", value: "v" },
  { label: "W", value: "w" },
  { label: "X", value: "x" },
  { label: "Y", value: "y" },
  { label: "Z", value: "z" },
];
export const categories = [
{ label: "All", value: "" },
  { label: "Generalities (000-099)", value: "generalities" },
  { label: "Philosophy/Psychology (100-199)", value: "philosophy/psychology" },
  { label: "Religion (200-299)", value: "religion" },
  { label: "Social Science (300-399)", value: "social science" },
  { label: "Language (400-499)", value: "language" },
  { label: "Natural Sciences & Mathematics (500-599)", value: "natural sciences & mathematics" },
  { label: "Technology (Applied Science) (600-699)", value: "technology (applied science)" },
  { label: "The Arts (700-799)", value: "the arts" },
  { label: "Literature and Rhetoric (800-899)", value: "literature and rhetoric" },
  { label: "Geography and History (900-999)", value: "geography and history" },
  { label: "Story Book", value: "story book" },

  // School Subjects
  { label: "Chemistry", value: "chemistry" },
  { label: "Christian", value: "christian" },
  { label: "English", value: "english" },
  { label: "Filipino", value: "filipino" },
  { label: "Geometry", value: "geometry" },
  { label: "Home Economics", value: "home economics" },
  { label: "Mathematics", value: "mathematics" },
  { label: "PEHM", value: "pehm" },
  { label: "Physics", value: "physics" },
  { label: "Science", value: "science" },
  { label: "Science & Health", value: "science & health" },
  { label: "Science & Technology", value: "science & technology" },
  { label: "Social Studies / Hekasi", value: "social studies / hekasi" },
  { label: "Statistics", value: "statistics" },
  { label: "Values", value: "values" },
  { label: "YDT", value: "ydt" },
];