
export const alphabetical = [
  { label: "Select letters", value: "" },
  { label: "A", value: "a" },
  { label: "B", value: "b" },
  { label: "C", value: "c" },
  { label: "D", value: "d" },
  { label: "E", value: "e" },
  { label: "F", value: "f" },
  { label: "G", value: "g" },
  { label: "H", value: "h" },
  { label: "I", value: "i" },
  { label: "J", value: "j" },
  { label: "K", value: "k" },
  { label: "L", value: "l" },
  { label: "M", value: "m" },
  { label: "N", value: "n" },
  { label: "O", value: "o" },
  { label: "P", value: "p" },
  { label: "Q", value: "q" },
  { label: "R", value: "r" },
  { label: "S", value: "s" },
  { label: "T", value: "t" },
  { label: "U", value: "u" },
  { label: "V", value: "v" },
  { label: "W", value: "w" },
  { label: "X", value: "x" },
  { label: "Y", value: "y" },
  { label: "Z", value: "z" },
];
export const categories = [
  // DDC Classification
  { label: "Generalities (000-099)", value: "generalities" },
  { label: "Philosophy/Psychology (100-199)", value: "philosophy/psychology" },
  { label: "Religion (200-299)", value: "religion" },
  { label: "Social Sciences (300-399)", value: "social sciences" },
  { label: "Language (400-499)", value: "language" },
  { label: "Natural Sciences & Mathematics (500-599)", value: "natural sciences & mathematics" },
  { label: "Technology / Applied Sciences (600-699)", value: "technology / applied sciences" },
  { label: "The Arts (700-799)", value: "the arts" },
  { label: "Literature & Rhetoric (800-899)", value: "literature & rhetoric" },
  { label: "Geography & History (900-999)", value: "geography & history" },

  // Textbook Categories
  { label: "Textbooks", value: "textbooks" },

  // Library Color-Coded Categories
  { label: "Love / Romance", value: "love / romance" },
  { label: "Novel", value: "novel" },
  { label: "Suspense / Thriller / Mystery / Action", value: "suspense / thriller / mystery / action" },
  { label: "Political", value: "political" },
  { label: "Literature", value: "literature" },
  { label: "Fiction", value: "fiction" },
  { label: "Non-Fiction", value: "non-fiction" },
  { label: "Biography", value: "biography" },
  { label: "Fantasy", value: "fantasy" },
  { label: "Documentary", value: "documentary" },
];

export const fields = [
  { label: "Logic", value: "logic" },
  { label: "Ethics", value: "ethics" },
  { label: "Political Science", value: "political science" },
  { label: "Economics", value: "economics" },
  { label: "Law", value: "law" },
  { label: "Public Administration", value: "public administration" },
  { label: "Education", value: "education" },
  { label: "Commerce", value: "commerce" },
  { label: "Customs", value: "customs" },
  { label: "Etiquette", value: "etiquette" },
  { label: "Folklore", value: "folklore" },
  { label: "Medicine", value: "medicine" },
  { label: "Engineering", value: "engineering" },
  { label: "Agriculture", value: "agriculture" },
  { label: "Home Economics", value: "home economics" },
  { label: "Architecture", value: "architecture" },
  { label: "Sculpture", value: "sculpture" },
  { label: "Drawing", value: "drawing" },
  { label: "Printing & Paintings", value: "printing & paintings" },
  { label: "Photography", value: "photography" },
  { label: "Music", value: "music" },
  {
    label: "Recreational & Performing Arts",
    value: "recreational & performing arts",
  },
];

export const subjects = [
  { label: "Chemistry", value: "chemistry" },
  { label: "Christian", value: "christian" },
  { label: "English", value: "english" },
  { label: "Filipino", value: "filipino" },
  { label: "Geometry", value: "geometry" },
  { label: "Home Economics", value: "home economics" },
  { label: "Mathematics", value: "mathematics" },
  { label: "PEHM", value: "pehm" },
  { label: "Physics", value: "physics" },
  { label: "Science", value: "science" },
  { label: "Science & Health", value: "science & health" },
  { label: "Science & Technology", value: "science & technology" },
  { label: "Social Studies / Hekasi", value: "social studies / hekasi" },
  { label: "Statistics", value: "statistics" },
  { label: "Values", value: "values" },
  { label: "YDT", value: "ydt" },
];

export const gradeLevels = [
  { label: "Grade 1", value: "grade 1" },
  { label: "Grade 2", value: "grade 2" },
  { label: "Grade 3", value: "grade 3" },
  { label: "Grade 4", value: "grade 4" },
  { label: "Grade 5", value: "grade 5" },
  { label: "Grade 6", value: "grade 6" },
  { label: "Secondary / Tertiary", value: "secondary / tertiary" },
];